/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminAvailabilityRouteImport } from './routes/_authenticated/admin/availability'
import { Route as AuthenticatedAdminBranchesRouteImport } from './routes/_authenticated/admin/branches'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin/customers'
import { Route as AuthenticatedAdminCyclesRouteImport } from './routes/_authenticated/admin/cycles'
import { Route as AuthenticatedAdminFarmOrderRouteImport } from './routes/_authenticated/admin/farm-order'
import { Route as AuthenticatedAdminItemsRouteImport } from './routes/_authenticated/admin/items'
import { Route as AuthenticatedAdminNonCollectionRouteImport } from './routes/_authenticated/admin/non-collection'
import { Route as AuthenticatedAdminOrderSheetsRouteImport } from './routes/_authenticated/admin/order-sheets'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminSuppliersRouteImport } from './routes/_authenticated/admin/suppliers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAvailabilityRoute =
  AuthenticatedAdminAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBranchesRoute =
  AuthenticatedAdminBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCyclesRoute =
  AuthenticatedAdminCyclesRouteImport.update({
    id: '/cycles',
    path: '/cycles',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFarmOrderRoute =
  AuthenticatedAdminFarmOrderRouteImport.update({
    id: '/farm-order',
    path: '/farm-order',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminItemsRoute = AuthenticatedAdminItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminNonCollectionRoute =
  AuthenticatedAdminNonCollectionRouteImport.update({
    id: '/non-collection',
    path: '/non-collection',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrderSheetsRoute =
  AuthenticatedAdminOrderSheetsRouteImport.update({
    id: '/order-sheets',
    path: '/order-sheets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSuppliersRoute =
  AuthenticatedAdminSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/availability': typeof AuthenticatedAdminAvailabilityRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/cycles': typeof AuthenticatedAdminCyclesRoute
  '/admin/farm-order': typeof AuthenticatedAdminFarmOrderRoute
  '/admin/items': typeof AuthenticatedAdminItemsRoute
  '/admin/non-collection': typeof AuthenticatedAdminNonCollectionRoute
  '/admin/order-sheets': typeof AuthenticatedAdminOrderSheetsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/availability': typeof AuthenticatedAdminAvailabilityRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/cycles': typeof AuthenticatedAdminCyclesRoute
  '/admin/farm-order': typeof AuthenticatedAdminFarmOrderRoute
  '/admin/items': typeof AuthenticatedAdminItemsRoute
  '/admin/non-collection': typeof AuthenticatedAdminNonCollectionRoute
  '/admin/order-sheets': typeof AuthenticatedAdminOrderSheetsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/availability': typeof AuthenticatedAdminAvailabilityRoute
  '/_authenticated/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/cycles': typeof AuthenticatedAdminCyclesRoute
  '/_authenticated/admin/farm-order': typeof AuthenticatedAdminFarmOrderRoute
  '/_authenticated/admin/items': typeof AuthenticatedAdminItemsRoute
  '/_authenticated/admin/non-collection': typeof AuthenticatedAdminNonCollectionRoute
  '/_authenticated/admin/order-sheets': typeof AuthenticatedAdminOrderSheetsRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin/audit'
    | '/admin/availability'
    | '/admin/branches'
    | '/admin/customers'
    | '/admin/cycles'
    | '/admin/farm-order'
    | '/admin/items'
    | '/admin/non-collection'
    | '/admin/order-sheets'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/suppliers'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/audit'
    | '/admin/availability'
    | '/admin/branches'
    | '/admin/customers'
    | '/admin/cycles'
    | '/admin/farm-order'
    | '/admin/items'
    | '/admin/non-collection'
    | '/admin/order-sheets'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/suppliers'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/availability'
    | '/_authenticated/admin/branches'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/cycles'
    | '/_authenticated/admin/farm-order'
    | '/_authenticated/admin/items'
    | '/_authenticated/admin/non-collection'
    | '/_authenticated/admin/order-sheets'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/suppliers'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/availability': {
      id: '/_authenticated/admin/availability'
      path: '/availability'
      fullPath: '/admin/availability'
      preLoaderRoute: typeof AuthenticatedAdminAvailabilityRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/branches': {
      id: '/_authenticated/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AuthenticatedAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cycles': {
      id: '/_authenticated/admin/cycles'
      path: '/cycles'
      fullPath: '/admin/cycles'
      preLoaderRoute: typeof AuthenticatedAdminCyclesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/farm-order': {
      id: '/_authenticated/admin/farm-order'
      path: '/farm-order'
      fullPath: '/admin/farm-order'
      preLoaderRoute: typeof AuthenticatedAdminFarmOrderRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/items': {
      id: '/_authenticated/admin/items'
      path: '/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AuthenticatedAdminItemsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/non-collection': {
      id: '/_authenticated/admin/non-collection'
      path: '/non-collection'
      fullPath: '/admin/non-collection'
      preLoaderRoute: typeof AuthenticatedAdminNonCollectionRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/order-sheets': {
      id: '/_authenticated/admin/order-sheets'
      path: '/order-sheets'
      fullPath: '/admin/order-sheets'
      preLoaderRoute: typeof AuthenticatedAdminOrderSheetsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/suppliers': {
      id: '/_authenticated/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AuthenticatedAdminSuppliersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminAvailabilityRoute: typeof AuthenticatedAdminAvailabilityRoute
  AuthenticatedAdminBranchesRoute: typeof AuthenticatedAdminBranchesRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminCyclesRoute: typeof AuthenticatedAdminCyclesRoute
  AuthenticatedAdminFarmOrderRoute: typeof AuthenticatedAdminFarmOrderRoute
  AuthenticatedAdminItemsRoute: typeof AuthenticatedAdminItemsRoute
  AuthenticatedAdminNonCollectionRoute: typeof AuthenticatedAdminNonCollectionRoute
  AuthenticatedAdminOrderSheetsRoute: typeof AuthenticatedAdminOrderSheetsRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSuppliersRoute: typeof AuthenticatedAdminSuppliersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminAvailabilityRoute: AuthenticatedAdminAvailabilityRoute,
    AuthenticatedAdminBranchesRoute: AuthenticatedAdminBranchesRoute,
    AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
    AuthenticatedAdminCyclesRoute: AuthenticatedAdminCyclesRoute,
    AuthenticatedAdminFarmOrderRoute: AuthenticatedAdminFarmOrderRoute,
    AuthenticatedAdminItemsRoute: AuthenticatedAdminItemsRoute,
    AuthenticatedAdminNonCollectionRoute: AuthenticatedAdminNonCollectionRoute,
    AuthenticatedAdminOrderSheetsRoute: AuthenticatedAdminOrderSheetsRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminSuppliersRoute: AuthenticatedAdminSuppliersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
