import {
  Apple,
  Banana,
  Bean,
  Beef,
  Carrot,
  Cherry,
  Citrus,
  Coffee,
  Cookie,
  CroissantIcon,
  Drumstick,
  Egg,
  Fish,
  Flower2,
  Grape,
  Ham,
  Leaf,
  LeafyGreen,
  Lollipop,
  Milk,
  Nut,
  Package,
  Pizza,
  Popcorn,
  Salad,
  Sandwich,
  Soup,
  Sprout,
  TreeDeciduous,
  TreePalm,
  Wheat,
  Grid2x2,
  IceCreamCone,
  CupSoda,
  Droplets,
  Flame,
  Candy,
  Beer,
  Utensils,
  ShoppingBasket,
  type LucideIcon,
} from "lucide-react";

/** Curated, searchable icon set for produce categories. */
export const CATEGORY_ICONS: { name: string; Icon: LucideIcon; keywords: string }[] = [
  { name: "leaf", Icon: Leaf, keywords: "leaf natural organic herb" },
  { name: "leafy-green", Icon: LeafyGreen, keywords: "greens spinach keerai leafy" },
  { name: "salad", Icon: Salad, keywords: "salad vegetables mixed" },
  { name: "carrot", Icon: Carrot, keywords: "carrot root vegetable kilangu" },
  { name: "sprout", Icon: Sprout, keywords: "sprout seedling microgreens" },
  { name: "wheat", Icon: Wheat, keywords: "wheat grain rice millet cereal" },
  { name: "bean", Icon: Bean, keywords: "beans pulses dal legume" },
  { name: "nut", Icon: Nut, keywords: "nuts dry fruit groundnut" },
  { name: "apple", Icon: Apple, keywords: "apple fruit" },
  { name: "banana", Icon: Banana, keywords: "banana fruit vazhai" },
  { name: "grape", Icon: Grape, keywords: "grape fruit" },
  { name: "cherry", Icon: Cherry, keywords: "cherry berry fruit" },
  { name: "citrus", Icon: Citrus, keywords: "lemon orange citrus" },
  { name: "tree-palm", Icon: TreePalm, keywords: "coconut palm tender" },
  { name: "tree", Icon: TreeDeciduous, keywords: "tree mango orchard" },
  { name: "flower", Icon: Flower2, keywords: "flower poo jasmine" },
  { name: "milk", Icon: Milk, keywords: "milk dairy curd" },
  { name: "egg", Icon: Egg, keywords: "egg protein" },
  { name: "fish", Icon: Fish, keywords: "fish seafood" },
  { name: "beef", Icon: Beef, keywords: "meat mutton beef" },
  { name: "drumstick", Icon: Drumstick, keywords: "chicken poultry" },
  { name: "ham", Icon: Ham, keywords: "meat cold cuts" },
  { name: "soup", Icon: Soup, keywords: "soup mix kootu ready" },
  { name: "cookie", Icon: Cookie, keywords: "snacks biscuit cookie" },
  { name: "croissant", Icon: CroissantIcon, keywords: "bakery bread" },
  { name: "sandwich", Icon: Sandwich, keywords: "bread sandwich" },
  { name: "pizza", Icon: Pizza, keywords: "ready to eat pizza" },
  { name: "popcorn", Icon: Popcorn, keywords: "snacks popcorn" },
  { name: "candy", Icon: Candy, keywords: "sweets candy mittai" },
  { name: "lollipop", Icon: Lollipop, keywords: "sweets kids" },
  { name: "ice-cream", Icon: IceCreamCone, keywords: "frozen dessert ice cream" },
  { name: "coffee", Icon: Coffee, keywords: "coffee tea beverage" },
  { name: "cup-soda", Icon: CupSoda, keywords: "juice drinks beverage" },
  { name: "beer", Icon: Beer, keywords: "drinks beverage" },
  { name: "droplets", Icon: Droplets, keywords: "oil honey liquid ghee" },
  { name: "flame", Icon: Flame, keywords: "spices masala hot" },
  { name: "utensils", Icon: Utensils, keywords: "kitchen cooking essentials" },
  { name: "package", Icon: Package, keywords: "packaged groceries staples" },
  { name: "basket", Icon: ShoppingBasket, keywords: "basket all items" },
  { name: "grid", Icon: Grid2x2, keywords: "all categories grid" },
];

const BY_NAME = new Map(CATEGORY_ICONS.map((i) => [i.name, i.Icon]));

export function categoryIcon(name?: string | null): LucideIcon {
  return (name && BY_NAME.get(name)) || Leaf;
}

export function searchCategoryIcons(q: string) {
  const t = q.trim().toLowerCase();
  if (!t) return CATEGORY_ICONS;
  return CATEGORY_ICONS.filter((i) => i.name.includes(t) || i.keywords.includes(t));
}
